<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>ghul.templates</PackageId>
    <Title>ghūl templates</Title>
    <Authors>degory</Authors>
    <PackageDescription>Templates for creating ghūl projects</PackageDescription>
    <Description>Templates for creating ghūl projects</Description>
    <PackageTags>dotnet-new;templates;ghul;ghūl;degory</PackageTags>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <PackageProjectUrl>https://ghul.dev</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ghul-lang/ghul-templates</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryBranch>main</RepositoryBranch>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>    
    <DebugType>None</DebugType>
    <PackageTags>ghul;ghūl;dotnet;.NET;template</PackageTags>
    <NoDefaultExcludes>true</NoDefaultExcludes>

    <TargetFramework>net10.0</TargetFramework>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>

    <PackageIcon>ghul-logo-icon.png</PackageIcon>
    <PackageIconUrl>ghul-logo-icon.png</PackageIconUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>  
    <None Include="LICENSE*" Pack="true" PackagePath="\" />
    <None Include="./images/ghul-logo-icon.png" Pack="true" PackagePath=""/>

    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

</Project>