<Project>
  <ItemGroup>
    <PackageVersion Include="ghul.runtime" Version="21.14.0" />
    <PackageVersion Include="example.classlib" Version="0.0.1-alpha.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.1" />
  </ItemGroup>
</Project>
